### ISSUE TITLE
The drawing operation Endding automatically

### ISSUE THREAD

**Issue by hiyahiya** [bozdoz/Leaflet.FreeHandShapes#1]
Thanks for this great plugin!
I have an issue with Chrome on mobile.
The drawing operation Endding automatically sometimes.

![image](https://user-images.githubusercontent.com/40639423/42213807-62d268bc-7eec-11e8-84e1-27975e53a655.png)
```
var drawLayers = new L.LayerGroup()
drawer = new L.FreeHandShapes({
	polygon: {
		color: '#2e6da4',
		fillColor: '#337ab7',
		weight: 3,
		smoothFactor: 1
	},
	polyline: {
		color: '#337ab7',
		smoothFactor: 0
	}
});

drawer.setMode('add');
drawLayers.addLayer(drawer);
drawLayers.addTo(map);
```
Thanks for your help!

**Comment by bozdoz** [comment]
Are you using iPhone?

**Comment by hiyahiya** [comment]
@bozdoz 
It's correct on iPhone. But the first drawing operation will endding automatically on Android or the mobile mode of PC Chrome 
![image](https://user-images.githubusercontent.com/40639423/42233119-271cfc2e-7f23-11e8-831f-be3bc6fda180.png)
![image](https://user-images.githubusercontent.com/40639423/42233190-5d590026-7f23-11e8-9954-0fe1440923b5.png)
I did not find out why the touchend event was triggered.
