### ISSUE TITLE
'Add layer' event fires prematurely on Android

### ISSUE THREAD

**Issue by Ivan-Perez** [bozdoz/Leaflet.FreeHandShapes#2]
Hi. First of all, thank you very much for this great library!

Take this example: http://app.cesens.com/f.php Touch the "Add" button in order to set the plugin to `add` mode. The first time you draw a line, the `touchend` event is fired too early (before you actually release your finger out the screen), and thus the 'layeradd' event of this plugin, provinding an incomplete polygon. But the next times you draw a line to make a polygon, it works as expected.

Here is a video showing the effect, just in case you can't replicate the behaviour: https://app.cesens.com/free-hand-shapes-demo.mp4 You can see that I try twice to draw the circle, as the first time always gets cancelled prematurely.

This always happens to me on Chrome for Android. The problem doesn't happen neither on iOS nor on desktop with a mouse.

Thanks!

**Comment by bozdoz** [comment]
Does it happen in the demo as well? https://bozdoz.github.io/leaflet-freehandshapes/

**Comment by Ivan-Perez** [comment]
No, it doesn't. So then there's something wrong on my code. I'm going to compare it and let you know.

Thanks for your fast response!

**Comment by Ivan-Perez** [comment]
Hi again!

The behaviour I'm seeing is a little bit weird. There's something I'm missing that is causing the library to start working badly. I'm trying to debug it, but with no results at the moment.

I have used your working demo as a starting point, and then I started removing things to have something more simple. These are things I've removed:

1. Substract features (allow overlapping polygons of different categories). Remove the turf web worker.
2. Buttons (and functions) to clear, delete or substract areas.
3. Categories (keep only one).

Interestingly, when I remove the categories, the plugin starts to exhibit the behaviour I described on the first post.

Here you have two examples, one before removing the categories (that just works) and another one with only one category (that doesn't work anymore), just in case you can test it or try to replicate the issue:

* https://app.cesens.com/f-ok.php
* https://app.cesens.com/f-bug.php

The difference between them: https://www.diffchecker.com/uyR9XKOy

Any help is appreciated. Thanks again!

**Comment by bozdoz** [comment]
That is strange.  Works fine on all other browsers?

**Comment by Ivan-Perez** [comment]
On desktop it works on every browser (tested Chrome, Firefox, IE11).
On mobile, it works fine on Safari (iOS), but not on Chrome/Opera (Android). Firefox for Android works also fine.

So it happens that the only browsers affected are those based on Chromium for Android.

**Comment by Ivan-Perez** [comment]
Calling `drawer.stopDraw()` before starting drawing the shape solves the problem.

Source code for that function:

```javascript
this.creating = false;
this.resetTracer();
this.drawStartedEvents('off');
this.setMapPermissions('enable');
```

I'm still looking for more details although for me the problem can be marked as resolved with that workaround.

**Edit:** Calling just `setMapPermissions('enable')` before drawing the first shape also solves my issue.
