### ISSUE TITLE
Event handlers are not cleaned up correctly when map is removed

### ISSUE THREAD

**Issue by avscta** [bozdoz/Leaflet.FreeHandShapes#24]
Hi everyone,

I would like to present 2 scenarios in which the plugin fails to cleaned up event handlers when the leaflet map is reinitialised

### Scenario 1
In this scenario, only importing the plugin without actually making any use of it will trigger the problem. When the map is first loaded you can click, zoom or pan without any trouble. However, when you reinitialise using the button, every interaction with the map will now trigger an error.

The bug happens due to these lines, which fail to pass the context in which the handlers should be de-registered (as well as 1 line calling "on" instead of "off"):
https://github.com/bozdoz/leaflet-freehandshapes/blob/dc7d98396bfde21e29db3c377db3348d15f9000f/dist/leaflet-freehandshapes.js#L17486-L17489

### Scenario 2
When the map is first loaded, it works fine, but when the map is reinitialised, you then get an error everytime you move the mouse out. This is the same issue referenced in #23 

The issue happens due to this line and needs the fix mentioned in #23 :
https://github.com/bozdoz/leaflet-freehandshapes/blob/dc7d98396bfde21e29db3c377db3348d15f9000f/dist/leaflet-freehandshapes.js#L17225

I will add relevant examples shortly.

**Comment by avscta** [comment]
### Scenario 1
https://github.com/certus-tech/leaflet-freehandshapes/blob/issue24/example/issue24_scenario1.html

### Scenario 2
https://github.com/certus-tech/leaflet-freehandshapes/blob/issue24/example/issue24_scenario2.html

**Comment by bozdoz** [comment]
Updated npm with 0.3.8

**Comment by avscta** [comment]
Fixes available in v0.3.9.

**Comment by avscta** [comment]
Fix for Scenario 1 reverted (accidentally?) in [commit](https://github.com/bozdoz/leaflet-freehandshapes/commit/06b58350fbe73af2d9f2156cdfa5d440b1143c70)

**Comment by avscta** [comment]
All fixes available in  v0.3.10
