### ISSUE TITLE
Touch support for Chrome

### ISSUE THREAD

**Issue by silvervesi** [bozdoz/Leaflet.FreeHandShapes#4]
How did you make this work on Chrome? I understand this plugin has been forked from FreeDraw, which doesn't work on Chrome.

Thanks in advance.

**Comment by bozdoz** [comment]
Yes, in fact I had to fork that library because it didn't work on mobile, maybe take a look at touch-extend (I believe there are some lines in there that I had to add):

https://github.com/bozdoz/leaflet-freehandshapes/blob/master/src/leaflet-touch-extend.js

**Comment by silvervesi** [comment]
Yes looks like this would be the answer indeed. However, we have decided to
write geometry creation from scratch. I might "borrow" the way you merge
polygons, though. It's awesome!

Thanks!

Sv.

**Comment by bozdoz** [comment]
For for it. Turf is a great library!
