### ISSUE TITLE
Not free-hand 

### ISSUE THREAD

**Issue by 00ricardo** [bozdoz/Leaflet.FreeHandShapes#5]
Hello my friend, I've been using freeDraw for a few months but it has some limitations that this plugin solves, I'm very interested in integrating it into my app.

- However, I am not able to create the polygons right. The free hand is not working for me, it must be something simple but I am not finding the problem. I did the following:

```

            require('leaflet-freehandshapes');
            var drawer = new L.FreeHandShapes({
                polygon: {
                    color: '#2e6da4',
                    fillColor: '#337ab7',
                    weight: 3,
                    smoothFactor: 1
                },
                polyline: {
                    color: '#337ab7',
                    smoothFactor: 0
                }
            });

            console.log(drawer)
  
            //change draw mode
            document.getElementById('mode').onchange = function() {
                switch (this.value) {
                    case 'nothing':
                        drawer.setMode('view');
                        break;
                    case 'draw':
                        drawer.addTo(mymap)
                        drawer.setMode('add');
                        break;
                    default:
                        break;
                }
            }
```

The result is this:
![1](https://user-images.githubusercontent.com/61938096/82122698-03e8e900-978d-11ea-8d70-749d644823ce.png)
Image 1
![2](https://user-images.githubusercontent.com/61938096/82122700-077c7000-978d-11ea-84dd-32db7b2c8060.png)
Image 2

As you can see, I'm trying to create a polygon with this shape, and the result is completely different.
I hope you can help me, thank you !!

**Comment by bozdoz** [comment]
The polygons are simplified; you may be able to adjust the simplification with the option defined here:

https://github.com/bozdoz/leaflet-freehandshapes/blob/master/src/index.js#L248-L273

Maybe try:

var drawer = new L.FreeHandShapes({
                polygon: {
                    color: '#2e6da4',
                    fillColor: '#337ab7',
                    weight: 3,
                    smoothFactor: 1
                },
                polyline: {
                    color: '#337ab7',
                    smoothFactor: 0
                },
                simplify_tolerance: 0,
            });

But it might be better to set it to a value a little higher than 0.  Maybe 0.0005

**Comment by bozdoz** [comment]
I might be wrong about that too.  Maybe try disabling concave_polygons.

concave_polygons: false

see here: https://github.com/bozdoz/leaflet-freehandshapes/blob/master/src/index.js#L25

**Comment by 00ricardo** [comment]
Hey my friend, thaks for your quick reply, it didnt work at first, but now its solve.

**- simplify_tolerance: 0,005 not working --> 0,001 working and of course with concave_polygons: false**

Can you please tell me if its posible to add the drawer to a LayerGroup? I want to enable/disable the draws with the leaflet-control. I tried `layerGroup.addLayer(drawer).addTo(map);`but it doesnt disable the draw.

**Comment by bozdoz** [comment]
Smooth factor maybe? It's almost definitely gotta be one of those options.

**Comment by 00ricardo** [comment]
I tried different values for the smooth and it doesn't work, hope the `drawer` could be part f a layerGroup

![1](https://user-images.githubusercontent.com/61938096/82135038-2c58fd80-97f6-11ea-8fe0-f28329126b81.png)
![2](https://user-images.githubusercontent.com/61938096/82135039-2e22c100-97f6-11ea-9de6-892fbf0e10e1.png)

The drawer was supposed to be disabled in the second img

**Comment by 00ricardo** [comment]
Hi @bozdoz , can you please help me with this issue? I appreciate !!

PS: Very nice plugin btw :)

**Comment by bozdoz** [comment]
I don't really understand the problem.  I see "Fire lines" selected and a red shape.  You're saying something is supposed to be disabled.  But I don't know what you're asking.

**Comment by 00ricardo** [comment]
The red shape is in a layer group. But when I disable the layer it's still there ... What I'm trying to do is enable/ disable the layer, that is, the red shape.

**Comment by bozdoz** [comment]
Do you have any code I could use to test/debug?

**Comment by 00ricardo** [comment]
1º Step:

Im creating "fire lines" with FreeHandShapes (red shapes). 

- Code [Step 1]

```
 var fireLines = new L.FreeHandShapes({
                polygon: {
                    color: 'red',
                    fillColor: 'red',
                    weight: 3,
                    smoothFactor: 1
                },
                polyline: {
                    color: '#D55F04',
                    smoothFactor: 0
                },
                simplify_tolerance: 0.001,
                merge_polygons: true,
                concave_polygons: false
            });
```
2º Step:

A select box with the modes. When i choose the option "Draw Fire lines" as you can see in  the code example:  I add the layer to a layerGroup called "fireLinesGroup" 

`fireLinesGroup.addLayer(fireLines).addTo(mymap);`

![Anotação 2020-05-20 222051](https://user-images.githubusercontent.com/61938096/82498603-332e8b80-9ae8-11ea-8a14-b6a8feca6e59.png)

- Code [Step 2]

```
 document.getElementById('mode').onchange = function() {
                switch (this.value) {
                    case 'nothing':
                        fireLines.setMode('view');
                        shadowLines.setMode('view');
                        break;
                    case 'draw-fl':
                        fireLinesGroup.addLayer(fireLines).addTo(mymap);
                        console.log(fireLinesGroup)
                        shadowLines.setMode('view');
                        fireLines.setMode('add');
                        break;         
                    case 'delete':
                        fireLines.setMode('delete');         
                        break;
                    default:
                        break;
                }
```


3º and final Step:

- Code [Step 3]

I add the` layerGroups` that cointaned all layers groups to Leaflet Controller, fireLinesGroup included, as you  can see in the code. 

```
var layerGroups = {
                    "Sensors": sensorGroup,
                    "Fire lines": fireLinesGroup
                }
var control = L.control.layers(mapTiles, layerGroups).addTo(mymap);

```

Hope i was clear enough! Thank you in advance =)

**Comment by 00ricardo** [comment]
Hmmm, I suppose that you didn't test it. 
Anyway thank you for your time! I really need this solve, i will try other ways.

**Comment by bozdoz** [comment]
Sorry; I've been busy with other projects.  I will have to reacquaint myself a bit with this project, as it's 3 years old.  I'll reply here if I find anything.

**Comment by bozdoz** [comment]
Running into issues getting it started.  I'm sorry I can't spend more time on this right now.

**Comment by 00ricardo** [comment]
Right... thanks anyways.

I think it is something that should be added to the plugin, an L.Control to the shapes that are added to the map, probably for each instance it would be perfect.

If you ever manage to take a look at this, please let me know.
